CREATE TABLE [db_backup].[EPPA Apr (Partial)]
(
[Customer_Full_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Batch_Number] [int] NULL,
[OCT_Reference_Number] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip_Code] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Terminal_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount] [float] NULL,
[Approval_Code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Auth_Message] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AVS_Response] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Card_Description] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Card_Present] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account_Data_MICR_Data] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original_Amount] [float] NULL,
[Original_Date_MMDDYY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original_Time_HHMMSS] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original_Transaction_Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Profile_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Record_Number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Tax] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_to_Name] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_to_Address1] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_to_Address2] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_to_City] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_to_State_Province] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_to_Postal_Code] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_to_Country] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Settle_Time] [datetime2] NULL,
[Card_Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Settle_Date] [datetime2] NULL,
[Company] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Completion_Date_MM_DD_YYYY] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Code] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cvv2_Response] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Departure_Date_MM_DD_YYYY] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Transaction_Status] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Transaction_Date] [datetime2] NULL,
[Transaction_Time] [datetime2] NULL,
[Transaction_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Transaction_Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Batch_Response] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Batch_SEQ_Number] [int] NULL,
[Email_Address] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Entry_Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Expiration_Date_MMYY] [int] NULL,
[First_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column_55] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
