CREATE TABLE [dbo].[tbl_feeschedule_dia]
(
[Billing Vendor Datasource] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tenant Id] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Procedure Group] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cpt Code] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cpt Description] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ ADVANTAGE 3T MRI ] [decimal] (28, 0) NULL,
[ CARLSBAD MDSAVE ] [decimal] (28, 0) NULL,
[ CLEVELAND KEMPTON ] [decimal] (28, 0) NULL,
[ COAL COUNTY EMPLOYEE CHEST XRAYS ] [decimal] (28, 0) NULL,
[ CT LUNG INTEGRIS BASS ENID ] [decimal] (28, 0) NULL,
[ EOMC CASH PAY ] [decimal] (28, 0) NULL,
[ EOMC TAKE CHARGE ] [decimal] (28, 0) NULL,
[ GREAT PLAINS ] [decimal] (28, 0) NULL,
[ HEALTHCHOICE SELECT MRI EVGH ] [decimal] (28, 0) NULL,
[ HOLDENVILLE IHS ] [decimal] (28, 0) NULL,
[ INTEGRIS CALCIUM SCORE, MIAMI ] [decimal] (28, 0) NULL,
[ INTEGRIS ENID BASS, OCCUPATIONAL ] [decimal] (28, 0) NULL,
[ INTEGRIS MIAMI OCC MED ] [decimal] (28, 0) NULL,
[ INVICTUS HEALTHCARE SPECIAL BILL ] [decimal] (28, 0) NULL,
[ MCCURTAIN EB6 MP MCP ] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ MCCURTAIN STG ] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ MCCURTAIN VES ] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NHS KEMPTON] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ OK SURGICAL HOSPITAL ] [decimal] (28, 0) NULL,
[ OSU TULSA OILERS ] [decimal] (28, 0) NULL,
[OSU UNIV HEALTH SERVICES] [decimal] (28, 0) NULL,
[ PROJECT WOMAN, DIA ] [decimal] (28, 0) NULL,
[ ROGER MILLS CALCIUM SCORE ] [decimal] (28, 0) NULL,
[ SHARE MEDICAL CENTER CALCIUM SCORING ] [decimal] (28, 0) NULL,
[ ST FRANCIS MUSKOGEE WWC ] [decimal] (28, 0) NULL,
[ ST MARYS ENID CASH PAY MAMMO ] [decimal] (28, 0) NULL,
[ TAHLEQUAH CITY HOSPITAL ] [decimal] (28, 0) NULL,
[ WEATHERFORD SPECIAL BILLING (CT CAL SCOR, OCT MAMMO, ALL OTH) ] [decimal] (28, 0) NULL,
[ WOODWARD CT SCORE, 90000000340 ] [decimal] (28, 0) NULL,
[ Woodward Industrial ] [decimal] (28, 0) NULL
) ON [PRIMARY]
GO
